### ISSUE TITLE
Go test errors with mssql

### ISSUE THREAD

**Issue by kiwih** [jinzhu/gorm#908] opened 2016-03-13 22:13 UTC
~~When using transactions the following error appears
`mssql: The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.`~~
Edit: Let's solve mssql errors one at a time

**Comment by jinzhu** [comment] 2016-03-13 23:52
Hi @kiwih 

Could you try to test on your local and point out how to fix the issue? as I can't test it out ;(

**Comment by kiwih** [comment] 2016-03-14 01:44
I am updating this issue to be the core source of mssql issues until we resolve them. I will perform whichever tests you would like. 

Running go test as it stands (after removing the non-compiling TestCompatabilityMode function) is as follows:
```
testing mssql...
[info] replacing callback `create` from D:/GoDev/src/github.com/jinzhu/gorm/callback_system_test.go:94
[info] removing callback `create` from D:/GoDev/src/github.com/jinzhu/gorm/callback_system_test.go:107

←[35m(mssql: IDENTITY_INSERT is already ON for table 'rogue.dbo.posts'. Cannot perform SET operation for table 'categories'.)←[0m
←[33m[2016-03-14 14:40:59]←[0m ←[31;1m ←[0m

←[35m(mssql: IDENTITY_INSERT is already ON for table 'rogue.dbo.posts'. Cannot perform SET operation for table 'categories'.)←[0m
←[33m[2016-03-14 14:40:59]←[0m ←[31;1m ←[0m

←[35m(mssql: Explicit value must be specified for identity column in table 'posts' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity
column.)←[0m
←[33m[2016-03-14 14:40:59]←[0m ←[31;1m ←[0m
--- FAIL: TestBelongsTo (0.01s)
        association_test.go:21: Got errors when save post mssql: Explicit value must be specified for identity column in table 'posts' either when IDENTITY_INSERT is set to ON or when a replication us
er is inserting into a NOT FOR REPLICATION identity column.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x55a610]

goroutine 207 [running]:
testing.tRunner.func1(0xc08267f8c0)
        c:/go/src/testing/testing.go:450 +0x178
github.com/jinzhu/gorm.(*Scope).related(0x0, 0x869fc0, 0xc0825085f0, 0xc082584290, 0x1, 0x1, 0x0)
        D:/GoDev/src/github.com/jinzhu/gorm/scope.go:947 +0x40
github.com/jinzhu/gorm.(*Association).Find(0xc0825b2270, 0x869fc0, 0xc0825085f0, 0xc0825b2270)
        D:/GoDev/src/github.com/jinzhu/gorm/association.go:19 +0xc8
github.com/jinzhu/gorm_test.TestBelongsTo(0xc08267f8c0)
        D:/GoDev/src/github.com/jinzhu/gorm/association_test.go:34 +0x3d2
testing.tRunner(0xc08267f8c0, 0xcbb5f0)
        c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
        c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0xa6c060, 0xcbb560, 0x7f, 0x7f, 0x869d01)
        c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc082571ef8, 0x86a3e0)
        c:/go/src/testing/testing.go:494 +0x77
main.main()
        github.com/jinzhu/gorm/_test/_testmain.go:312 +0x11d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 11 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0824f2960)
        c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
        c:/go/src/database/sql/sql.go:481 +0x33d
exit status 2
FAIL    github.com/jinzhu/gorm  0.467s
```

**Comment by kiwih** [comment] 2016-03-14 01:44
I believe that SET IDENTITY_INSERT ON must only be done when you are in fact inserting a record with a known identity. Otherwise, it must be left off

**Comment by jinzhu** [comment] 2016-03-14 08:46
Hi @kiwih 

Are you using `github.com/jinzhu/gorm/dialects/mssql`? I think it is only set `IDENTITY_INSERT ON` for inserting

**Comment by kiwih** [comment] 2016-03-15 02:13
Hi @jinzhu,

I'm using your main_test.go file, and the import is indeed present.

Cheers

**Comment by jordanchapian** [comment] 2016-05-25 20:18
I am experiencing this. If I attempt an insertion without explicitly specifying the fields constituting the PK, I get an error. So what is the appropriate logic here? I feel that if we do explicitly specify all PK fields on creation, we should be setting `IDENTITY_INSERT ON`, and if no PK fields are set, we should omit this.

For example, the current implementation is as follows:

```go
func setIdentityInsert(scope *gorm.Scope) {
	if scope.Dialect().GetName() == "mssql" {
		scope.NewDB().Exec(fmt.Sprintf("SET IDENTITY_INSERT %v ON", scope.TableName()))
	}
}
```

And I believe this would accomplish what I stated above.

```go
func setIdentityInsert(scope *gorm.Scope) {
	if scope.Dialect().GetName() == "mssql" {
		for _, b := range scope.PrimaryFields() {
        if b.IsBlank == false {
            scope.NewDB().Exec(fmt.Sprintf("SET IDENTITY_INSERT %v ON", scope.TableName()))
            break
        }
    }
	}
}
```

**Comment by devint1** [comment] 2016-05-31 16:31
I am also observing this when inserting into a MS SQL database. The change provided by @jordanchapian seemed to fix the issue for me.

Also, #941 may be a duplicate of this.

**Comment by jordanchapian** [comment] 2016-06-02 21:14
@devint1 My proposal above is not entirely correct. If `IDENTITY_INSERT` is set to on for table x, and you attempt to turn `IDENTITY_INSERT` on for table y, mssql will throw an error like ` IDENTITY_INSERT is already ON for table x` 

When I encountered this, I split `setIdentityInsert(scope *gorm.Scope)` into an intro and outro callback to ensure that  `IDENTITY_INSERT` is turned off after the transaction.

I have a fork with these changes.

**Comment by ryanwalls** [comment] 2016-11-16 00:39
Any updates on getting these changes merged into the mssql driver?

**Comment by jbfm** [comment] 2017-02-21 16:01
Why would `IDENTITY_INSERT` be enabled at all by default? Most common use-case is probably to let the database itself handle primary keys. Or am I wrong?

**Comment by LuisBosquez** [comment] 2017-03-15 22:13
@jinzhu, have these changes been merged? I am also finding this issue, even when following the basic tutorial here: http://jinzhu.me/gorm/crud.html#create 

By the way, SQL Server is now available on [Linux and Docker](http://docs.microsoft.com/en-us/sql/linux/) which means you don't need windows to test them :)

**Comment by jbfm** [comment] 2017-03-16 08:26
@LuisBosquez I've opened a PR to remove the automatic IDENTITY_INSERT entirely, #1379, no progress or comments on that though.

Easiest fix at the moment is to just manually apply the changes in that PR, and vendor Gorm.

**Comment by jinzhu** [comment] 2017-03-16 14:09
@LuisBosquez thank you for let me know the docker thing, let me test it!

**Comment by LuisBosquez** [comment] 2017-03-16 19:49
@jinzhu this is the official Docker image [mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/) I am one of the owners of the project. Currently working on a set of tutorials for SQL Server with GoLang in our new SQL Server [tutorials website](http://aka.ms/sqldev) So please let me know if you plan to integrate this fix anytime soon :)

**Comment by jinzhu** [comment] 2017-03-17 08:46
Hi @LuisBosquez 

I have tried to setup test environment with the docker, but can't login database `gorm` with account `gorm`  (able to login with `sa`), anything I missed?

```
CREATE LOGIN gorm WITH PASSWORD = 'LoremIpsum86' ;
CREATE DATABASE gorm;
sp_addrole 'gorm' , 'db_owner';
```

**Comment by LuisBosquez** [comment] 2017-03-17 18:17
@jinzhu I tried to repro your issue, but it worked for me. Did you 'USE master' when you created the account? What's the error message you're seeing?

**Comment by jinzhu** [comment] 2017-03-18 00:25
@LuisBosquez 

Maybe this could help you finger out the issue easily 

![image](https://cloud.githubusercontent.com/assets/6843/24067174/1a963a3a-0bb4-11e7-9d84-677b7c3fc834.png)

Here is my searched solution, but not sure how to do that in a linux docker http://www.sherweb.com/blog/the-server-principal-a-is-not-able-to-access-the-database-b-under-the-current-security-context-microsoft-sql-server-error-916/

**Comment by LuisBosquez** [comment] 2017-03-19 03:29
@jinzhu Funny, I hadn't encountered that error before. What's the command you're using to run the docker image? The website mentions that this issue is related to setting up a different collation. Are you using one? How did you set it up?

**Comment by jinzhu** [comment] 2017-03-19 03:57
I am using docker kitematic https://github.com/docker/kitematic started docker image (microsoft/mssql-server-linux), and only set environment `ACCEPT_EULA`, `SA_PASSWORD`, haven't setup any other things

**Comment by LuisBosquez** [comment] 2017-03-21 21:20
@jinzhu I found the error. You are missing a step after creating the login and the database. You need to create a USER for the "gorm" database. The steps should be as it follows:

**under "sa":**
```
CREATE LOGIN gorm WITH PASSWORD = 'LoremIpsum86' ;
CREATE DATABASE gorm;
USE gorm;
CREATE USER gorm FROM LOGIN gorm -- links the user "gorm" to the login within the database.
sp_addrole 'gorm' , 'db_owner';
```

after that you can now run: `mssql -s localhost -u gorm -p LoremIpsum86`

and then: 
```
USE gorm
```

**Comment by jinzhu** [comment] 2017-03-22 09:43
@LuisBosquez thank you, it works!

a little problem in your code is the last line should be:

`sp_changedbowner 'gorm';

but not

`sp_addrole 'gorm' , 'db_owner';`

**Comment by jinzhu** [comment] 2017-03-22 15:54
Hi @all, Fixed all tests for mssql  👏

**Closed by jinzhu** 2017-03-22 15:54 UTC
Labels: driver:mssql

**Comment by smithaitufe** [comment] 2019-02-20 12:23
Hello I am having issues with MSSQL Server.

I tried to run an update statement and it failed.

```go
tx := db.Begin()
	var m model.Menu
	if err := tx.Where("LOWER(code) = LOWER(?)", menu.Code).Find(&m).Error; err != nil && err == gorm.ErrRecordNotFound {
		fmt.Println("menu with code", menu.Code, "does not exist")
		handleError(tx, tx.Create(&menu))
	} else {
		m.Position = menu.Position
		m.Component = menu.Component
		m.Title = menu.Title
		m.Code = menu.Code
		handleError(tx, tx.Where("id = ?", m.ID).Find(&model.Menu{}).Updates(&m))
		menu = m
	}
	tx.Commit()
```
Please what is the recommended solution to updating in gorm when using MSSQL Server?
