### ISSUE TITLE
How Do I Do Bulk Insert

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#1098] opened 2016-06-30 09:45 UTC
I have a pretty large slice that needs to be inserted into the database, but I am worried this will be slow if I iterate using transaction.

Is there a way to do bulk insert or am I stuck to using transaction?

**Comment by ezra-g** [comment] 2016-07-01 18:44
This appears to be a duplicate of https://github.com/jinzhu/gorm/issues/255. (Also, +1).

**Closed** 2016-07-04 22:44 UTC
Labels: duplicated
