### ISSUE TITLE
Many2Many performs extra Updates.

### ISSUE THREAD

**Issue by chris-ramon** [jinzhu/gorm#329] opened 2015-01-06 08:24 UTC
```go
type Language struct {
    Id   int
    Name string
}

type User struct {
    Id        int
    Name      string
    Languages []Language `sql:"many2many:user_languages;"`
}

db.Model(&user).Association("Languages").Append([]Language{languageZH})
```
Last line will perform the following queries:
1. UPDATE `users` SET ...
2. UPDATE `languages` SET ..
3. INSERT INTO `user_languages` ...

@jinzhu any idea why I am getting extra `updates` ?

Note: `&user` and `languageZH` remains unmodified.

**Comment by jinzhu** [comment] 2015-01-12 13:46
Should be caused by the dirty implement of `Append`, let me think a better solution to avoid the unnecessary Update 

Thank you for your report.

**Comment by chris-ramon** [comment] 2015-01-12 16:18
> Should be caused by the dirty implement of Append, let me think a better solution to avoid the unnecessary Update
> 
> Thank you for your report.

:+1:

**Comment by OscarSwanros** [comment] 2015-01-27 23:39
Is it possible to define a self-referencing `many2many` relationship?

I'm doing 
```
type User struct {
	Id int64
	Contacts []User `gorm:"many2many:user_contacts;"`
}
```
but getting `pq: column "user_id" specified more than once` error.

**Comment by dorajistyle** [comment] 2015-01-28 10:22
I've found  the solution of self-referencing many2many relationship. :smiley: 

    type User struct {
        Id int64
        Contacts []User `gorm:"foreignkey:user_id;associationforeignkey:contact_id;many2many:user_contacts;"`
    }

**Comment by OscarSwanros** [comment] 2015-01-28 14:52
Awesome! Thanks @dorajistyle :dancer: 

Worked a charm!

**Comment by euforic** [comment] 2015-04-04 22:18
Any updates on a way to do this with out the extra update?

**Comment by jinzhu** [comment] 2015-04-10 09:19
Hi All,

The issue should be fixed, thank you.

**Closed by jinzhu** 2015-04-10 09:19 UTC

**Comment by rvenugopal** [comment] 2015-06-27 07:46
is this working for anyone?  I am still experiencing extra updates.  I just want to create an association between two models (insert a record in the intersection table).  The following fires extra updates

```
db.Model(&model.Business{Id: businessId}).
		Association("Users").
		Append(model.User{Id: userId})
```

**Comment by olivoil** [comment] 2015-06-30 06:41
It still does extra and unwanted updates for me too, it tries to update both tables before inserting the joint record, instead of only inserting the joint record.

**Comment by LiranCohen** [comment] 2015-07-01 16:12
Yeah I still get extra unwanted updates w/ many2many associations ass well.

**Comment by damnpoet** [comment] 2015-07-15 15:30
+1 Same error here... any workaround?
