### ISSUE TITLE
all: add context.Context as the first parameter ?  Cannot properly trace http API calls all the way through GORM's sql calls with data dog

### ISSUE THREAD

**Issue by bjm88** [jinzhu/gorm#2400] opened 2019-04-15 11:41 UTC
I'm using the latest versions of Go, Gin, Gorm, and DataDog go tracer.  The goal is to see in datadog console (or other APM monitor service like New Relic) the api calls from http level of app via GIN, and follow that trace all the way down to what SQL calls it makes.  This is a common observability goal of modern stacks.  It seems this cannot be done if Gorm does not support some level of Go's Context to link the two....  Thread from DataDog here:
https://github.com/DataDog/dd-trace-go/issues/226

It would be great to be able to initialize and provide Gorm some way to get or wrap a context when taking a connection out of the connection pool.  Any way this is possible today?

**Comment by odeke-em** [comment] 2019-05-20 14:56
Thank you @bjm88 for filing this issue! Perhaps could we re-title it to "all: add context.Context as the first parameter"?

I just encountered this issue too.

Aside from propagating traces, some more benefits of having context.Context https://golang.org/pkg/context/ https://blog.golang.org/context as the first parameter:
* Cancellation of calls e.g. when a client leaves or 
* Deadlines e.g. kill long running queries/took too long, a customer has requested that we kill this query

**Comment by emirb** [comment] 2019-05-23 06:22
Closing as duplicate of https://github.com/jinzhu/gorm/issues/1231. Should be addressed soon.

**Closed by emirb** 2019-05-23 06:22 UTC
