### ISSUE TITLE
Deep association only populating first result

### ISSUE THREAD

**Issue by Gacnt** [jinzhu/gorm#760] opened 2015-12-13 06:44 UTC
I have these structs:
```
// User is the User table in the database
type User struct {
	gorm.Model
	Username     string `sql:"not null;unique"`
	Email        string `sql:"not null;unique"`
	PasswordHash string `sql:"not null;unique"`
	UserLevel    int    `sql:"not null;default:0"`
	Characters   []Characters
	MainPosts    []ForumMainThreadsPosts
	ReplyPosts   []ForumMainPostsReplies
}

// Characters is a table in the database
type Characters struct {
	gorm.Model
	UserID          int    `sql:"index"`
	CharacterName   string `sql:"not null;unique"`
	CharacterServer string `sql:"not null"`
	CharacterLevel  int    `sql:"not null"`
	CharacterMain   bool   `sql:"not null"`
	CharacterClass  string `sql:"not null"`
	CharacterPic    string `sql:"not null"`
}
type ForumMainThreadsPosts struct {
	gorm.Model
	UserID             int `sql:"index"`
	ForumMainThreadsID int `sql:"index"`
	User               User
	ForumMainThreads   ForumMainThreads
	Title              string `sql:"not null;unique"`
	Body               string `sql:"type:text;not null"`
	Sticky             bool   `sql:"not null;default:0"`
	Views              int    `sql:"not null;default:0"`
	ReplyCount         int    `sql:"not null;default:0"`
	Replies            []ForumMainPostsReplies
}

```

Then I call:
```
db.Where("forum_main_threads_id = ?", vals["threadid"]).Preload("User").Preload("User.Characters").Preload("ForumMainThreads").Find(&forumPosts)

for _, post := range forumPosts {
                log.Println("LOOPING ONCE")
		log.Println(post.User)
		log.Println(post.User.Characters)
}
```

each loop is the exact same `User.ID` so I don't understand why the first one gets populated but the second one doesnt

Then what I get from the loop is:

```
2015/12/12 23:46:19 LOOPING ONCE
2015/12/12 23:46:19 {{1 2015-12-13 00:02:35 +0000 UTC 2015-12-13 00:02:35 +0000 UTC <nil>} Gacnt email@email.com 0 [{{1 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC <nil>} 1 Murgon Mal'Ganis 100 true Warrior http://render-api-us.worldofwarcraft.com/static-render/us/internal-record-3684/30/119827486-avatar.jpg?alt=/wow/static/images/2d/avatar/2-0.jpg}] [] []}
2015/12/12 23:46:19 [{{1 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC <nil>} 1 Murgon Mal'Ganis 100 true Warrior http://render-api-us.worldofwarcraft.com/static-render/us/internal-record-3684/30/119827486-avatar.jpg?alt=/wow/static/images/2d/avatar/2-0.jpg}]
2015/12/12 23:46:19 LOOPING ONCE
2015/12/12 23:46:19 {{1 2015-12-13 00:02:35 +0000 UTC 2015-12-13 00:02:35 +0000 UTC <nil>} Gacnt email@email.com asd 0 [] [] []}
2015/12/12 23:46:19 []

```

if I do 
```
	for _, post := range forumPosts {
		characters := []common.Characters{}
		db.Model(&post.User).Related(&characters)
		log.Println(characters)
	}
```

I get the data I'm expecting

**Comment by Gacnt** [comment] 2015-12-15 02:15
Anybody got any information on this?

**Comment by jinzhu** [comment] 2015-12-15 02:57
Please follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md

**Comment by Gacnt** [comment] 2015-12-15 23:22
@jinzhu Thanks for the reply and I'm loving `gorm` unfortunately the code is just too proprietary to replicate, I tried to provide enough information. I was hoping maybe you could see how I was calling the query to the database maybe I was doing it wrong.

**Comment by jinzhu** [comment] 2015-12-16 00:50
Not sure about the problem, and this should be tested, so should be fine.

As even you can't reproduce the issue, it would be pretty time costing for me to check it, and don't even know it is a real problem or misusage, so going to close it.

Feel free to reopen it when you could provide reproducible demo.

Thank you.

**Closed by jinzhu** 2015-12-16 00:50 UTC
