### ISSUE TITLE
Gorm can create a poorly formatted SQL join query missing any ON conditions

### ISSUE THREAD

**Issue by cmip** [jinzhu/gorm#655] opened 2015-09-11 22:22 UTC
Today, in one of my Gorm-based apps, an instance was creating a bad SQL query that was failing on the DB server.  Specifically, on Go code like:
```
.Select("foo.*").Model(&Bar{Id: in}).Related(&foo, "Foo")
```
...the runtime query would be created and would be missing a JOIN condition.  IE. in the SQL "... ON <join condition> WHERE ...", the <join_condition> text would simply be missing.

I can confirm that restarting the bad instance caused the problem I saw to go away for now.  The app instance is able to create these join queries successfully again.

Commit edc1f785 seems like a potential great fix this issue, but unfortunately from what I can tell the bad instance was using an executable that was built using a Gorm version with that fix.

May I ask if you're confident the race condition fix you landed should completely solve the issue?

Other than the presence of this bug and my understanding that the app instance is using a Gorm version with the fix, I don't have a reason to believe the code fix in edc1f785 is incorrect.  Working through the code, it seems like for this to happen, join_table_handler.go's line 141 s.Destination.ForeignKeys has to be empty.  Those appear to be set up indirectly in model_struct.go, too.

And the fix you added appears good to me so far.  Maybe I'm missing something.

I propose to add a panic to Gorm in join_table_handler.go before line 162 if joinConditions is zero-length.  That would at least highlight if the join associations aren't loaded correctly and prevent an obviously incorrect SQL query from being executed.  What do you think?  If you agree, I would happy to create the CL and send a pull request.  Or if it would be faster, you may prefer to add it yourself.

Please let me know if there's any data I can get you about the issue I saw or any help I can give.  Thanks.

**Comment by jinzhu** [comment] 2015-09-14 14:36
Hi @chsmp 

If possible, could you write some tests that could reproduce your issue?

**Comment by chsmp** [comment] 2015-09-15 00:01
Hi @jinzhu, unfortunately, I specifically have not been able to write a test to reproduce this issue because the error doesn't happen consistently for us.

So far I've only seen the issue in our production app environment, never in development or in testing.  We restart our app instances in our production environment multiple times a day.  Friday was the first time I saw this issue in 6+ months of those restarts.  Since that restart on Friday, the issue hasn't resurfaced and appears to have gone away.

I understand if there's not enough info for now and you need to close this issue until more data comes in.  I will be happy to provide any extra info that comes along in case we see the issue again.  Thank you.

**Closed** 2016-01-03 13:20 UTC
Labels: #query, #relation
