### ISSUE TITLE
json, gorm and sql tokens in tags

### ISSUE THREAD

**Issue by vkulikov** [jinzhu/gorm#622] opened 2015-08-16 18:31 UTC
Hi!
Thanks for GORM, first of all!

Maybe it's a newbie question but where can be found information about usage json, gorm and sql tokens in tag descriptions for struct fields? Also, full list of values for gorm token will be useful.
And how gorm will interpret tag's value like this: `sql:"foo" json:"bar"`

Thank you!

**Comment by robvdl** [comment] 2015-08-16 20:01
Gorm will only look at the sql: and gorm: tags (correct me if I am wrong), the json: tag are used by the Go JSON library if you marshal a struct to JSON.

**Comment by zasran** [comment] 2015-08-26 23:02
Duplicate of issue #608

**Comment by jinzhu** [comment] 2015-09-11 00:07
Hi All

I suggest only used documented tags in the README, all other tags don't promise any compatibility.

But be sure to let me know what is missing when develop your application.

![image](https://cloud.githubusercontent.com/assets/6843/9804049/dbd68186-585b-11e5-85ad-5e6231fe7198.png)

**Closed by jinzhu** 2015-09-11 00:07 UTC
