### ISSUE TITLE
[bug]SingularTable 导致panic sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by chnzrb** [jinzhu/gorm#2344] opened 2019-03-20 05:59 UTC
// SingularTable use singular table by default
func (s *DB) SingularTable(enable bool) {
	modelStructsMap = sync.Map{}
	s.parent.singularTable = enable
}
 在运行过程中， 并发该函数可能会产生竞争关系， 导致panic sync: unlock of unlocked mutex。

fatal error: sync: unlock of unlocked mutex

goroutine 8817 [running]:
runtime.throw(0xbbdcf0, 0x1e)
        C:/Go/src/runtime/panic.go:617 +0x72 fp=0xc0002109e0 sp=0xc0002109b0 pc=0x42d342
sync.throw(0xbbdcf0, 0x1e)
        C:/Go/src/runtime/panic.go:603 +0x35 fp=0xc000210a00 sp=0xc0002109e0 pc=0x42d2c5
sync.(*Mutex).Unlock(0x119f880)
        C:/Go/src/sync/mutex.go:184 +0xc1 fp=0xc000210a28 sp=0xc000210a00 pc=0x463661
sync.(*Map).Store(0x119f880, 0xb86860, 0xb7f2e0, 0xad97a0, 0xc000216780)
        C:/Go/src/sync/map.go:162 +0x269 fp=0xc000210ad0 sp=0xc000210a28 pc=0x461de9
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc000772b80, 0x0)
        F:/GOHOME/src/github.com/jinzhu/gorm/model_struct.go:615 +0x1390 fp=0xc000210d80 sp=0xc000210ad0 pc=0x8dc6f0
github.com/jinzhu/gorm.(*Scope).PrimaryField(0xc000772b80, 0xaacdc0)
        F:/GOHOME/src/github.com/jinzhu/gorm/scope.go:164 +0x2f fp=0xc000210db8 sp=0xc000210d80 pc=0x8de58f
github.com/jinzhu/gorm.queryCallback(0xc000772b80)
        F:/GOHOME/src/github.com/jinzhu/gorm/callback_query.go:36 +0xc6d fp=0xc000210f88 sp=0xc000210db8 pc=0x8bf32d
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc000772b80, 0xc0001d1a40, 0x3, 0x4, 0x0)
        F:/GOHOME/src/github.com/jinzhu/gorm/scope.go:867 +0x88 fp=0xc000210fb8 sp=0xc000210f88 pc=0x8e7358
github.com/jinzhu/gorm.(*DB).First(0xc000236000, 0xa83980, 0xc00000ea48, 0x0, 0x0, 0x0, 0xc00000ea38)
        F:/GOHOME/src/github.com/jinzhu/gorm/main.go:309 +0x128 fp=0xc000211040 sp=0xc000210fb8 pc=0x8d51f8
myadmin_h5/models.GetServerNode(...)

可参考：https://github.com/golang/go/issues/26480

**Comment by chnzrb** [comment] 2019-03-20 06:02
可参考https://github.com/golang/go/issues/26480

**Comment by emirb** [comment] 2019-04-14 06:53
Duplicate of https://github.com/jinzhu/gorm/issues/2344

**Closed by emirb** 2019-04-14 06:53 UTC
