### ISSUE TITLE
time.Time in go1.8

### ISSUE THREAD

**Issue by ihaiker** [jinzhu/gorm#1478] opened 2017-05-17 15:41 UTC
error info :
sql: Scan error on column index 4: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

type Admin struct {
    ID        uint64 `gorm:"primary_key"`
    Name      string `gorm:"column:name;size:32"`
    Email     string `gorm:"null;unique;size:128"`
    Password  string `gorm:"not null;size:32"`

    CreatedAt time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP"`
    UpdatedAt time.Time `gorm:"column:updated_at;type:datetime;"`
}

**Comment by mswartzendruberISP** [comment] 2017-05-17 21:10
Using MySQL? This appears to be a duplicate of #958, which can be solved by adding "?parseTime=true" to your connection string.

**Closed** 2017-05-18 02:22 UTC
