### ISSUE TITLE
Seems that Last and First does not work with SQLITE

### ISSUE THREAD

**Issue by BertVerhees** [jinzhu/gorm#1730] opened 2018-01-18 15:36 UTC
### What version of Go are you using (`go version`)?
1.9.2

### Which database and its version are you using?
SQLite3

### What did you do?
Create a table with two users, and query for the last and the first user. In both cases the same user is returned.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"log"
	"database/sql"
	"time"
	"fmt"
)

type User struct {
	gorm.Model
	Birthday     time.Time
	Age          int
	Name         string  `gorm:"size:255"` // Default size for string is 255, reset it with this tag
	Num          int     `gorm:"AUTO_INCREMENT"`

	CreditCard        CreditCard      // One-To-One relationship (has one - use CreditCard's UserID as foreign key)
	Emails            []Email         // One-To-Many relationship (has many - use Email's UserID as foreign key)

	BillingAddress    Address         // One-To-One relationship (belongs to - use BillingAddressID as foreign key)
	BillingAddressID  sql.NullInt64

	ShippingAddress   Address         // One-To-One relationship (belongs to - use ShippingAddressID as foreign key)
	ShippingAddressID int

	IgnoreMe          int `gorm:"-"`   // Ignore this field
	Languages         []Language `gorm:"many2many:user_languages;"` // Many-To-Many relationship, 'user_languages' is join table
}

type Email struct {
	ID      int
	UserID  int     `gorm:"index"` // Foreign key (belongs to), tag `index` will create index for this column
	Email   string  `gorm:"type:varchar(100);unique_index"` // `type` set sql type, `unique_index` will create unique index for this column
	Subscribed bool
}

type Address struct {
	ID       int
	Address1 string         `gorm:"not null;unique"` // Set field as not nullable and unique
	Address2 string         `gorm:"type:varchar(100);unique"`
	Post     sql.NullString `gorm:"not null"`
}

type Language struct {
	ID   int
	Name string `gorm:"index:idx_name_code"` // Create index with name, and will create combined index if find other fields defined same name
	Code string `gorm:"index:idx_name_code"` // `unique_index` also works
}

type CreditCard struct {
	gorm.Model
	UserID  uint
	Number  string
}


func CreateAndQueryTables(){
	db, err := gorm.Open("sqlite3", "/tmp/test.db")
	if err!=nil {
		log.Println(err.Error())
	}
	defer db.Close()
	db.CreateTable(&CreditCard{})
	db.CreateTable(&Language{})
	db.CreateTable(&Address{})
	db.CreateTable(&Email{})
	db.CreateTable(&User{})
	user := User{
		Name:            "jinzhu",
		BillingAddress:  Address{Address1: "1Billing Address - Address 1",Address2: "2Billing Address - Address 2",Post:sql.NullString{"a",true}},
		ShippingAddress: Address{Address1: "11Shipping Address - Address 1",Address2: "12Billing Address - Address 2",Post:sql.NullString{"a",true}},
		Emails:          []Email{
			{Email: "jinzhu@example.com"},
			{Email: "jinzhu-2@example@example.com"},
		},
		Languages:       []Language{
			{Name: "ZH"},
			{Name: "EN"},
		},
	}
	db.Create(&user)
	db.Save(&user)
	user = User{
		Name:            "Pietje",
		BillingAddress:  Address{Address1: "21Billing Address - Address 2",Address2: "22Billing Address - Address 2",Post:sql.NullString{"a",true}},
		ShippingAddress: Address{Address1: "31Shipping Address - Address 2",Address2: "32Billing Address - Address 2",Post:sql.NullString{"a",true}},
		Emails:          []Email{
			{Email: "Pietje@example.com"},
			{Email: "Pietje-2@example@example.com"},
		},
		Languages:       []Language{
			{Name: "ZH"},
			{Name: "EN"},
		},
	}
	db.Create(&user)
	db.Save(&user)
	var u User
	db.First(&u)
	fmt.Println(u.ID)
	db.Last(&u)
	fmt.Println(u.ID)
//the following lines show that the two users exist
       var users []User
	db.Find(&users)
	fmt.Println(users)
}

func main(){
	CreateAndQueryTables()
}

**Comment by Aetheus** [comment] 2018-02-05 17:22
Hi there, @BertVerhees . I've had a look at your code, and I've found the issue that's causing the problem. If you enable debug mode (````db.LogMode(true)````) the problem becomes much clearer.

The issue is that, when you called "First" and passed the reference to "u" to it, it saved the result of that query naturally into "u" (````SELECT * FROM "users"  WHERE "users".deleted_at IS NULL ORDER BY "users"."id" ASC LIMIT 1````). So, "u" now has an ID of 1, since that's the result of the query (the first row) and is exactly what you expected. 

When you call "Last" and pass the reference to "u" to it, it considers the fields of "u" to be query parameters. Therefore, it looks for the "last" result ... that has an ID of "1". Which is, naturally, the same result as before (```` SELECT * FROM "users"  WHERE "users".deleted_at IS NULL AND "users"."id" = '1' ORDER BY "users"."id" DESC LIMIT 1````) and probably *not* what you wanted.

This is your code with some comments and the debug log enabled to show exactly what's happening: https://gist.github.com/Aetheus/53abf941bd8bc52599a6ff4d369fccbe

And this is likely what you wanted to do instead:
https://gist.github.com/Aetheus/9e00b0367c9fb13cb8b02bd19520684e

Tell me if this solves your issue, and if it does, perhaps @jinzhu can close this issue.

**Comment by BertVerhees** [comment] 2018-02-06 09:10
Thanks for your sharp view, Aetheus, it solves my problem.

**Closed** 2018-02-06 09:10 UTC
