### ISSUE TITLE
Auto migrate not creating foreign key in database

### ISSUE THREAD

**Issue by kumarsiva07** [jinzhu/gorm#1448] opened 2017-04-25 21:48 UTC
```
type Account struct {
     ID uint64 `gorm:"primary_key;AUTO_INCREMENT"`
     Name           string `gorm:"type:varchar(100)"`
     Users          []User
}

```
```
type User struct  {
   ID uint64 `gorm:"primary_key;AUTO_INCREMENT"`
   Account          Account `gorm:"ForeignKey:AccountID;AssociationForeignKey:Refer"`
   AccountID        uint64
}
```

models.DB.AutoMigrate(&models.Account{}, &models.User{})

This migration not creating foreign key in mysql.

**Comment by zardak** [comment] 2017-04-26 07:53
Duplicate of https://github.com/jinzhu/gorm/issues/450

**Closed** 2018-02-12 09:45 UTC
